apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: grafana-backend-config
  namespace: grafana 
spec:
  healthCheck:
    type: HTTP
    requestPath: /api/health
    port: 3000
  timeoutSec: 300